Runs into error
jstroem/ng-input-currency pull request #1
Opened 2017-01-05 15:10 UTC by HarpoMarx69

'modelCtrl.$options.getOption is not a function'
on AngularJS 1.6.1 without this

2017-01-06 06:54 UTC, jstroem commented
Looks good. Ill merge it in the weekend.

2017-01-20 20:07 UTC, aspcanada requested changes

2017-01-20 20:07 UTC, aspcanada commented on src/ng-input-currency.js
> +    $ngModel.$options = ngModel.$options.createChild({
Don't you want $ngModel? (missing $)

2017-01-20 20:44 UTC, jstroem commented
This has been fixed and made possible to use both >1.6 and <1.6 versions of angular.

2017-01-20 20:44 UTC, closed without merging